### ISSUE TITLE
Ambiguity in broadcasted(+, ::IntervalBox, ::IntervalBox)

### ISSUE THREAD

**Issue by schillic** [JuliaIntervals/TaylorModels.jl#39] opened 2019-04-17 19:12 UTC
(I was not sure whether to report in `IntervalArithmetic.jl` or here. Feel free to move around.)

Since a few days the following does not work anymore.
```julia
julia> using TaylorIntegration
julia> using TaylorModels: @taylorize
julia> using IntervalArithmetic: IntervalBox
julia> using TaylorModels: validated_integ

julia> @taylorize function vanderPol!(t, x, dx)
    local μ = 1.0
    dx[1] = x[2]
    dx[2] = (μ * x[2]) * (1 - x[1]^2) - x[1]
    return dx
end

julia> validated_integ(vanderPol!, [0., 1.], IntervalBox([0., 1.]), 0., 1., 2, 2, 1e-2)

ERROR: MethodError: Base.Broadcast.broadcasted(::typeof(+), ::IntervalBox{2,Float64}, ::IntervalBox{2,Float64}) is ambiguous. Candidates:
  broadcasted(f, X::IntervalBox, Y::IntervalBox) in IntervalArithmetic at .julia/packages/IntervalArithmetic/9q80F/src/multidim/arithmetic.jl:27
  broadcasted(f, X::IntervalBox, y) in IntervalArithmetic at .julia/packages/IntervalArithmetic/9q80F/src/multidim/arithmetic.jl:28
  broadcasted(f, x, Y::IntervalBox) in IntervalArithmetic at .julia/packages/IntervalArithmetic/9q80F/src/multidim/arithmetic.jl:29
  broadcasted(f::Union{typeof(*), typeof(+), typeof(muladd)}, arg1, arg2, args...) in DiffEqBase at .julia/packages/DiffEqBase/EFqMn/src/diffeqfastbc.jl:54
Possible fix, define
  broadcasted(::Union{typeof(*), typeof(+), typeof(muladd)}, ::IntervalBox, ::IntervalBox)
Stacktrace:
 [1] #validated_integ#31(::Int64, ::Bool, ::Function, ::Function, ::Function, ::Array{Float64,1}, ::IntervalBox{2,Float64}, ::Float64, ::Float64, ::Int64, ::Int64, ::Float64) at .julia/packages/TaylorModels/DXLdP/src/validatedODEs.jl:277
 [2] validated_integ(::Function, ::Array{Float64,1}, ::IntervalBox{2,Float64}, ::Float64, ::Float64, ::Int64, ::Int64, ::Float64) at .julia/packages/TaylorModels/DXLdP/src/validatedODEs.jl:265
```
It is quite mysterious because there were no changes in this package.

**Comment by dpsanders** [comment] 2019-04-17 19:14
What is DiffEqBase doing in there? Is that relevant?

**Comment by schillic** [comment] 2019-04-17 19:17
I don't think it is relevant, but who knows, and I did not investigate any further so far. I obtained the error message above in a fresh Julia session, so I guess one of the packages in the code above must have loaded that.

**Comment by dpsanders** [comment] 2019-04-17 19:27
Ah, I guess TaylorIntegration loads it.

I have no idea what is going on here...

**Comment by lbenet** [comment] 2019-04-17 20:05
Thanks for reporting!

> What is DiffEqBase doing in there? Is that relevant?

DiffEqBase is used by `TaylorIntegration.jl` to a common interface (be callable from DiffEquations).

I can't reproduce the problem, i.e., everything runs fine in my set-up. Can you provide your current set-up (branches you are using)?

**Comment by schillic** [comment] 2019-04-17 20:38
I use the release version of all the packages mentioned above in Julia v1.1. Our Travis build has the same error.
* TaylorIntegration v0.4.1
* TaylorModels v0.1.0
* IntervalArithmetic v0.15.2

As I said above, it all worked fine until recently (precisely six days ago, see [our build history](https://github.com/JuliaReach/Reachability.jl/commits/master?before=475f8c61f4b4629db983b1ac99c3a5a742f03d2e+35)).
Maybe there was a problem with the change to `General` (I don't really think so, but it is really a strange thing).

**Comment by schillic** [comment] 2019-04-18 14:40
We use `+` instead of `.+` now in [this place](https://github.com/JuliaIntervals/TaylorModels.jl/blob/746a848ed5bd493500c9499433f2f6825c77df2d/src/validatedODEs.jl#L277) to avoid broadcasting (see [here](https://github.com/JuliaReach/Reachability.jl/commit/eec22154d7e7810ad8222a72e2089f3f4fe4f1e8#diff-4d25d35d0c7ef535840d280ae5d6652dR41)).

**Comment by schillic** [comment] 2019-04-18 15:08
Another observation: Travis and I use Linux. @mforets uses a Mac and does not have this problem.

**Comment by lbenet** [comment] 2019-04-18 15:40
For the record, I also work in a Mac and had no issue.

@schillic Does avoiding broadcasting solves the problem? In terms of performance, i do not know what is better in this case, but this can be easily fixed in TaylorModels.

**Comment by lbenet** [comment] 2019-04-18 15:41
@dpsanders What about adding the possible fix to `IntervalArithmetic.jl`?
```julia
Possible fix, define
  broadcasted(::Union{typeof(*), typeof(+), typeof(muladd)}, ::IntervalBox, ::IntervalBox)
```

**Comment by schillic** [comment] 2019-04-18 15:43
> Does avoiding broadcasting solve the problem?

Yes, because there is no call to `broadcasted` (obviously :wink:).

**Comment by mforets** [comment] 2019-04-19 13:59
As the error suggests, the problem is particular to `IntervalArithmetic` and is triggered if you load `DiffEqBase` (the function that creates the ambiguity is [this one](
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/diffeqfastbc.jl#L53)).

Consider the following minimal example:

```julia
julia> using IntervalArithmetic

julia> B = IntervalBox(0..1, 0..1);

julia> B .+ B
[0, 2] × [0, 2]

julia> using DiffEqBase # using v5.6.4 here

julia> B .+ B
ERROR: MethodError: Base.Broadcast.broadcasted(::typeof(+), ::IntervalBox{2,Float64}, ::IntervalBox{2,Float64}) is ambiguous. Candidates:
  broadcasted(f, X::IntervalBox, Y::IntervalBox) in IntervalArithmetic at /Users/forets/.julia/dev/IntervalArithmetic/src/multidim/arithmetic.jl:27
  broadcasted(f, X::IntervalBox, y) in IntervalArithmetic at /Users/forets/.julia/dev/IntervalArithmetic/src/multidim/arithmetic.jl:28
  broadcasted(f, x, Y::IntervalBox) in IntervalArithmetic at /Users/forets/.julia/dev/IntervalArithmetic/src/multidim/arithmetic.jl:29
  broadcasted(f::Union{typeof(*), typeof(+), typeof(muladd)}, arg1, arg2, args...) in DiffEqBase at /Users/forets/.julia/packages/DiffEqBase/EFqMn/src/diffeqfastbc.jl:54
Possible fix, define
  broadcasted(::Union{typeof(*), typeof(+), typeof(muladd)}, ::IntervalBox, ::IntervalBox)
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by dpsanders** [comment] 2019-04-19 14:17
So it seems like DiffEqBase is defining something too broad - in particular, it is committing type piracy by defining operations only on Base types.

**Comment by mforets** [comment] 2019-04-19 14:58
Alright, and how should we proceed?

1) Report in DiffEqBase asking if `DiffEqBase.broadcasted` can be annotated with `arg1` and/or `arg2` as a `DiffEqBC`.

2) Try the possible fix `broadcasted(::Union{typeof(*), typeof(+), typeof(muladd)}, ::IntervalBox, ::IntervalBox)`.

CC: @ChrisRackauckas

**Comment by ChrisRackauckas** [comment] 2019-04-19 15:04
You're not supposed to annotate `broadcasted` args, only the ones with an array style. This is just replacing what's in Base with a patched version that should be coming to Julia soon anyways, fixing the aliasing issue. Why is `broadcasted(f, X::IntervalBox, Y::IntervalBox)` defined in the first place? You shouldn't be doing that.

>Just like all the other machinery, broadcasted also computes and exposes the combined broadcast style of its arguments, so instead of specializing on broadcasted(f, args...), you can specialize on broadcasted(::DestStyle, f, args...) for any combination of style, function, and arguments.

https://docs.julialang.org/en/v1/manual/interfaces/#extending-in-place-broadcast-1

**Comment by lbenet** [comment] 2019-04-25 03:45
This issue be at least partially fixed by https://github.com/PerezHz/TaylorIntegration.jl/pull/68. 

Note also that https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/211 was merged, where the exported `broadcasted` methods that caused the ambiguity were commented.

**Comment by lbenet** [comment] 2019-04-28 20:45
https://github.com/PerezHz/TaylorIntegration.jl/pull/68 is now merged, and should have solved the problem reported here. Can you confirm @schillic ?

**Comment by schillic** [comment] 2019-04-29 06:51
I still use the release version of `TaylorIntegration`, so the update there cannot have an influence for me. However, it still works now. The reason I guess is that the `broadcasted` overload in `DiffEqBase` got removed.

**Comment by mforets** [comment] 2019-05-13 16:06
I think this can be closed. Thanks!

**Comment by lbenet** [comment] 2019-05-13 16:08
Closing.

**Closed by lbenet** 2019-05-13 16:08 UTC
